"""docs/sample_analysis/performance/: predict.py-generated frontend fixtures vs docs/performance.schema.draft.json.

The samples come from tools/make_performance_samples.py (run it to regenerate). This test only reads them: every
file is marked synthetic, wraps an unchanged predict.py block that validates against the draft schema, and the
no-number states carry no number anywhere in the block.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = ROOT / "docs/sample_analysis/performance"
SCHEMA = ROOT / "docs/performance.schema.draft.json"
sys.path.insert(0, str(ROOT / "tools"))

FIXTURE = "SYNTHETIC — generated by tools/make_performance_samples.py from test fixtures; numbers are meaningless"
NO_NUMBERS = ("not_trained", "out_of_scope")


def _samples():
    return sorted(SAMPLES.glob("*.json"))


def _load(p):
    return json.loads(p.read_text())


def _numbers(x, path="performance"):
    """Every int/float (not bool) anywhere in ``x``, with its path."""
    if isinstance(x, bool):
        return []
    if isinstance(x, (int, float)):
        return [path]
    if isinstance(x, dict):
        return [n for k, v in x.items() for n in _numbers(v, f"{path}.{k}")]
    if isinstance(x, list):
        return [n for i, v in enumerate(x) for n in _numbers(v, f"{path}[{i}]")]
    return []


def test_the_state_coverage_is_there():
    files = _samples()
    assert files, f"no samples in {SAMPLES}; run tools/make_performance_samples.py"
    blocks = {p.name: _load(p)["performance"] for p in files}
    assert {b["model_status"] for b in blocks.values()} == {"not_trained", "research_preview", "validated",
                                                           "out_of_scope"}
    assert {b["clip_in_training"] for b in blocks.values()} == {"no", "train_oof", "lockbox"}
    assert any(b["retrospective"] and b["clip_in_training"] == "no" and b["drivers"] for b in blocks.values())
    assert (SAMPLES / "README.md").exists()
    for name in blocks:
        assert f"`{name}`" in (SAMPLES / "README.md").read_text(), f"{name} is not described in the README"


def test_the_schema_is_valid_draft_2020_12():
    jsonschema = pytest.importorskip("jsonschema")
    schema = _load(SCHEMA)
    assert schema["$schema"] == "https://json-schema.org/draft/2020-12/schema"
    jsonschema.Draft202012Validator.check_schema(schema)


@pytest.mark.parametrize("path", _samples(), ids=lambda p: p.name)
def test_sample_is_marked_synthetic_and_validates(path):
    jsonschema = pytest.importorskip("jsonschema")
    doc = _load(path)
    assert doc["_fixture"] == FIXTURE
    assert set(doc) == {"_fixture", "_scenario", "performance"}
    blk = doc["performance"]
    jsonschema.Draft202012Validator(_load(SCHEMA)).validate(blk)
    assert any(w.startswith("SYNTHETIC") for w in blk["warnings"])  # dry-run worker outputs
    if blk["model_status"] in NO_NUMBERS:
        assert _numbers(blk) == [], f"{path.name}: numbers in a {blk['model_status']} block"
        assert blk["engagement"] is None and blk["reach"] is None and blk["drivers"] == []
        assert blk["reason"]
    else:
        e = blk["engagement"]
        assert e["percentile_deal_platform"] is not None and e["likely_range"] is not None
        assert blk["context"]["account_level"] is (e["percentile_account"] is not None)


def test_the_schema_rejects_numbers_in_a_no_number_state():
    jsonschema = pytest.importorskip("jsonschema")
    schema = _load(SCHEMA)
    scored = next(_load(p)["performance"] for p in _samples()
                  if _load(p)["performance"]["model_status"] == "research_preview")
    for status in NO_NUMBERS:
        bad = {**scored, "model_status": status, "reason": "x"}
        with pytest.raises(jsonschema.ValidationError):
            jsonschema.validate(bad, schema)
        with pytest.raises(jsonschema.ValidationError):
            jsonschema.validate({**bad, "engagement": None, "reach": None}, schema)  # drivers still there
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate({**scored, "engagement": None}, schema)


def test_the_schema_matches_predict_constants():
    """The enums the draft pins are the ones predict.py uses."""
    predict = pytest.importorskip("predict")
    schema = _load(SCHEMA)
    d = schema["$defs"]
    assert set(d["platform"]["enum"]) == set(predict.PLATFORMS)
    assert set(d["target_prediction"]["properties"]["target"]["enum"]) == {predict.PRIMARY, predict.REACH}
    assert set(d["driver"]["properties"]["family"]["enum"]) == set(predict.FAMILY_LABELS)


def test_the_doc_example_validates():
    """PRODUCT_PIPELINE.md §3's JSON example follows the tool output (the draft schema)."""
    jsonschema = pytest.importorskip("jsonschema")
    doc = (ROOT / "docs/PRODUCT_PIPELINE.md").read_text()
    sec = doc.split("### JSON example", 1)[1]
    body = sec.split("```json", 1)[1].split("```", 1)[0].strip()
    assert body.startswith('"performance":')
    blk = json.loads("{" + body + "}")["performance"]
    jsonschema.Draft202012Validator(_load(SCHEMA)).validate(blk)
