#!/usr/bin/env python3
"""Frontend fixtures for the proposed ``performance`` block, generated by the real tools/predict.py.

Builds the SYNTHETIC study of tests/test_predict.py (its own fixture builders: planted-signal worker outputs,
two deals x two platforms, fit_models.py --save-model), then runs ``predict.main`` (the CLI) once per UI state
and writes each block wrapped with a ``_fixture`` marker. predict.py's block is written unchanged under
``performance``. The numbers are meaningless: they only show the shape and the states.

    .venv/bin/python tools/make_performance_samples.py --out docs/sample_analysis/performance

Runs offline on CPU in about a minute (two small fit_models.py evaluations). No network, no pods, no DB.
``model_version``, ``provenance.model_git`` and the ``perf-...+YYYYMMDD.<commit>`` stamp change from run to run.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
for p in (ROOT, ROOT / "tools", ROOT / "tests"):
    sys.path.insert(0, str(p))

import predict  # noqa: E402
import test_predict as tp  # noqa: E402  (fixture builders: make_study, make_served, write_clip_in)

FIXTURE = "SYNTHETIC — generated by tools/make_performance_samples.py from test fixtures; numbers are meaningless"
NEW_CTX = ["--width", "1080", "--height", "1920", "--audio-mean-db", "-20"]
LABELS = {"deal-a": "Deal A (synthetic)", "deal-b": "Deal B (synthetic)"}


def run_predict(npz: Path, model_dir: Path, featurizer: Path, args: list[str], tmp: Path) -> dict:
    out = tmp / "block.json"
    out.unlink(missing_ok=True)
    rc = predict.main([str(npz), "--featurizer", str(featurizer), "--model-dir", str(model_dir), *args,
                       "--out", str(out)])
    if rc != 0:
        raise SystemExit(f"predict.py exited {rc} for {npz.name} {args}")
    return json.loads(out.read_text())


def status_of(model_dir: Path) -> str:
    man = json.loads((model_dir / "manifest.json").read_text())
    return predict.model_status_from(man["targets"][predict.PRIMARY]["metrics"], man["feature_set"], man["model"])[0]


def build(out_dir: Path, work: Path, log=print) -> dict[str, str]:
    """Write the samples into ``out_dir``; returns {file name: model_status}."""
    log("building the synthetic study (tests/test_predict.py fixtures) ...")
    study = tp.make_study(work)
    log("fitting a stage-1 model (content CV only, lockbox not scored) ...")
    preview = tp.make_served(study, "model_cv", score_lockbox=False)
    log("fitting a model with the lockbox scored (--score-lockbox) ...")
    scored = tp.make_served(study, "model_lb")
    fz, new = study["featurizer"], study["new"] / "worker-9" / "n000.npz"
    # the fixture's worker JSONs carry no modalities: state the audio track in the context (as an upload would);
    # --no-audio overrides it for the out-of-scope sample
    audio = work / "has_audio.json"
    audio.write_text(json.dumps({"has_audio": True}))
    base = ["--context", str(audio), *NEW_CTX]
    ctx_new = ["--deal-id", "deal-a", "--deal-label", LABELS["deal-a"], "--platform", "tiktok", *base]
    samples: list[tuple[str, str, dict]] = []

    def add(name, scenario, block):
        samples.append((name, scenario, block))

    # not_trained: no saved model at all (the honest state until stage 1 passes)
    add("not_trained.json", "No saved performance model (tonight's state). New clip, deal-a on TikTok.",
        run_predict(new, work / "no-model", fz, ctx_new, work))

    # not_trained after a fit whose stage-1 GO rule failed: a copy of the preview model with its GO metrics
    # edited down (as tests/test_predict.py::test_not_trained_has_no_numbers does)
    failed = work / "model_go_failed"
    shutil.copytree(preview, failed)
    man = json.loads((failed / "manifest.json").read_text())
    man["targets"][predict.PRIMARY]["metrics"]["go"]["content"] = {"point": 0.01, "ci": [-0.01, 0.03]}
    (failed / "manifest.json").write_text(json.dumps(man))
    add("not_trained_go_failed.json",
        "A model was fit but did not pass the pre-registered stage-1 GO rule. The manifest's GO metrics were "
        "edited to a failing value to produce this state; predict.py itself is unchanged.",
        run_predict(new, failed, fz, ctx_new, work))

    # research_preview: stage-1 GO passed, lockbox not scored
    st = status_of(preview)
    if st != "research_preview":
        raise SystemExit(f"the stage-1 fixture model is {st}, expected research_preview")
    add("research_preview.json", "Synthetic model that passes stage-1 GO; new (unposted) clip, deal-a on TikTok, "
        "with a known account (account-level percentile shown).",
        run_predict(new, preview, fz, [*ctx_new, "--account-id", "acc-deal-a-tiktok-0"], work))
    add("research_preview_no_account.json", "Same model and clip, no account given: deal x platform level only.",
        run_predict(new, preview, fz, ctx_new, work))

    # validated: only if the lockbox-scored fixture model really clears the lockbox rule
    st_lb = status_of(scored)
    if st_lb == "validated":
        add("validated.json", "Synthetic model whose own lockbox within-stratum rho has a CI lower bound > 0 "
            "(fit with --score-lockbox). New clip, deal-a on TikTok, known account.",
            run_predict(new, scored, fz, [*ctx_new, "--account-id", "acc-deal-a-tiktok-0"], work))
    else:
        log(f"validated: skipped (the lockbox-scored fixture model is {st_lb})")

    # out_of_scope: > 90 s, and no audio track
    rng = np.random.default_rng(90)
    d = work / "scope"
    d.mkdir(exist_ok=True)
    long = tp.write_clip_in(d, "s-long", study["groups"], study["v"], 2.0, rng, {"duration_s": 120.0})
    add("out_of_scope_too_long.json", "Clip is 120 s, outside the 5-90 s training scope.",
        run_predict(long, preview, fz, ctx_new, work))
    add("out_of_scope_no_audio.json", "Clip has no audio track (--no-audio).",
        run_predict(new, preview, fz, [*ctx_new, "--no-audio"], work))

    # a training clip: its out-of-fold prediction, ranked without itself, no drivers
    import pandas as pd

    ref = pd.read_csv(preview / f"reference_{predict.PRIMARY}.csv", dtype={"video_id": str})
    single = ref.groupby("video_id")["platform"].transform("size") == 1
    r = ref[single].sort_values("video_id").iloc[0]
    add("train_oof.json", f"A training clip ({r['video_id']}) asked about in its own deal x platform: out-of-fold "
        "prediction, retrospective, drivers omitted.",
        run_predict(tp._clip(study, r["video_id"]), preview, fz,
                    ["--deal-id", r["deal_id"], "--deal-label", LABELS[r["deal_id"]], "--platform", r["platform"],
                     *base], work))

    # retrospective: a new (not trained-on) clip that was already posted
    add("retrospective.json", "A new clip that is already posted (--posted-at): retrospective prediction, drivers "
        "shown.", run_predict(new, preview, fz, [*ctx_new, "--posted-at", "2026-09-20T18:30:00Z"], work))

    # sealed lockbox clip: scored normally, never an observed outcome
    lvid = sorted(study["lock"])[0]
    ldeal = study["sel"].set_index("video_id").loc[lvid, "deal_id"]
    add("lockbox.json", f"A sealed lockbox clip ({lvid}): scored, retrospective, never show its observed outcome.",
        run_predict(tp._clip(study, lvid), preview, fz,
                    ["--deal-id", ldeal, "--deal-label", LABELS[ldeal], "--platform", "tiktok", *base], work))

    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("*.json"):  # stale samples only: never a file this script did not write
        try:
            ours = json.loads(old.read_text()).get("_fixture") == FIXTURE
        except (ValueError, AttributeError):
            ours = False
        if ours:
            old.unlink()
    written = {}
    for name, scenario, block in samples:
        doc = {"_fixture": FIXTURE, "_scenario": scenario, "performance": block}
        (out_dir / name).write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
        written[name] = block["model_status"]
        log(f"  {name}: {block['model_status']}, clip_in_training={block['clip_in_training']}, "
            f"retrospective={block['retrospective']}")
    return written


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--out", type=Path, default=ROOT / "docs/sample_analysis/performance")
    ap.add_argument("--keep-work", type=Path, default=None, help="build in this directory and keep it (debugging)")
    args = ap.parse_args(argv)
    from threadpoolctl import threadpool_limits

    with threadpool_limits(1):
        if args.keep_work:
            args.keep_work.mkdir(parents=True, exist_ok=True)
            build(args.out, args.keep_work)
        else:
            with tempfile.TemporaryDirectory(prefix="perf-samples-") as tmp:
                build(args.out, Path(tmp))
    return 0


if __name__ == "__main__":
    sys.exit(main())
